Fix map attribute name
benhutchins/dyngoose pull request #600
Opened 2022-08-08 16:01 UTC by cbumstead

## Fix map attribute name

#### Breaking Change

### Why did you make these changes?

To support using attribute name when using a map attribute

### What's changed in these changes?

Modified map.ts, added a unit test

### What do you especially want to get reviewed?

map.ts changes

### Submission Type

* [x ] Bugfix

### All Submissions

* [x] Have you added an explanation of what your changes?
* [x] Have you written new tests for your changes, as applicable?
* [ ] Have you checked potential side effects that could make bad impacts to other services?

2022-08-08 16:38 UTC, benhutchins commented
I appreciate the pull request @cbumstead!

I'll need to revise your edits to `package.json` before merging, but we can definitely get this merged in.

2022-10-10 20:14 UTC, benhutchins requested changes

2022-10-10 20:14 UTC, benhutchins commented on package.json
> +  "name": "@hixme/dyngoose",
Don't want to rename the package here.

2022-10-10 20:14 UTC, benhutchins commented on package.json
> +  "version": "3.2.0",
Do not need to manually bump the version for release, this is done automatically from the CI release process.

2023-04-10 01:14 UTC, cbumstead commented
thanks,  I revised the package.json

2023-04-10 05:47 UTC, benhutchins commented
@cbumstead Thank you so much for keeping this PR alive with your recent update. I was reviewing it to get it merged in noticed the implementation was changing the way the map attribute's `attributes` object mapped from attribute names to property names. I pulled your change in and revised it to keep it consistent with the way the table attributes work, but this issue has been fixed in the new release 4.1.0.

Also, love the vscode launch config addition. Makes sense to help others who use vscode and the integrated debugger functionality.

Thank you for the contribution!

2023-04-10 05:47 UTC, closed without merging